


data_quality:
  checks:
    - representativeness
    - stability
    - outliers
    - completeness
    - uniqueness

models:
  pd_model:
    general:
      subranges:
        - LTV
        - CREDIT_SCORE
        - INCOME
        - AGE
        - EMPLOYMENT_STATUS
        - ARREARS
        - EAD
        - PD
        - LGD
      variables:
        - PD_score
        - LGD_score
        - intodefault_flag
        - default_flag
        - realized_lgd
        - exposure_at_default
      metrics:
        - homogeneity
        - heterogeneity
        - distribution_fit
        - feature_importance
        - feature_stability
        - feature_correlation
        - feature_interaction
        - feature_relevance
      thresholds:
          homogeneity: 0.7
          heterogeneity: 0.3
          distribution_fit: 0.05
          feature_importance: 0.1
          feature_stability: 0.1
          feature_correlation: 0.8
          feature_interaction: 0.05
          feature_relevance: 0.1
      variables:
        - 

    calibration:
      metrics:
        - jeffreys_test
        - brier_score
        - reliability_diagrams
        - normal_calibration_test
        - binomial_calibration_test
        - correlated_defaults_test
        - chi_square_test
        - hosmer_lemeshow
    
    discrimination:
      metrics:
        - auc
        - auc_delta
        - roc_curve
        - pietra_index
        - ks_stat
        - cap_curve
        - gini
        - gini_ci
        - cier
        - kl_distance
        - information_value
        - kendalls_tau
        - accuracy_ratio
        - spearmans_rho
      thresholds:
        auc: 0.7
        gini: 0.4
        ks_stat: 0.4
    
    stability:
      metrics:
        - migration_matrix
        - migration_stability
        - rating_concentration
        - psi
        - csi
        - jensen_shannon
        - anova
      thresholds:
        psi: 0.25
        csi: 0.25
        anova: 0.05
        jensen_shannon: 0.05

  lgd_model:
    calibration:
      metrics:
        - t_test
        - r_squared
        - rmse
        - correlation
        - mean_error
        - mse
        - mann_whitney
      thresholds:
        t_test: 0.05
        r_squared: 0.6
        rmse: 0.1
        correlation: 0.5
        mean_error: 0.05
        mse: 0.1        
        mann_whitney: 0.05
        

    
    discrimination:
      metrics:
        - gauc
        - gauc_delta
        - spearmans_rho
        - vus
        - lorenz_curve
        - somers_d
        - kendalls_tau
      thresholds:
        gauc: 0.6
    
    stability:
      metrics:
        - psi
      thresholds:
        psi: 0.25

reporting:
  output_format: html
  output_dir: reports/
  include_plots: true
  save_results: true

alerts:
  email: false
  threshold_breach: true
  export_format: json